nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['https://tu-dominio-angular.com', 'http://localhost:4200']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': ~
